stages:
 make_dataset:
  cmd: python .\src\data\make_dataset.py .\data\raw\data1.csv .\data\raw\data2.csv 
  deps:
  - .\src\data\make_dataset.py 
  - .\data\raw\data1.csv 
  - .\data\raw\data2.csv
  

 build_features:
  cmd: python .\src\features\build_features.py .\data\processed\
  deps:
  - .\src\features\build_features.py 
  - .\data\processed\


 train_model:
   cmd: python .\src\models\train_model.py .\data\preprocessed\
   deps:
   - .\src\models\train_model.py 
   - .\data\preprocessed\
   

 push_model:
   cmd: python .\src\models\push_model.py 
   deps:
   - .\src\models\train_model.py 
   

# visualize:
#   cmd: python .\src\visualization\visualize.py .\models\model.joblib .\data\preprocessed\
#   deps:
#   - .\src\visualization\visualize.py 
#   - .\models\model.joblib 
#   - .\data\preprocessed\


   

metrics:
- dvclive\metrics.json